services:
  todo-postgres:
    container_name: todo-env-postgres
    image: postgres:18.4-bookworm
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql

  todo-redis:
    container_name: todo-env-redis
    image: redis:8.6.1
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    restart: always

  todo-postgres-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations

  port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: todo-env-port-forwarder
    entrypoint: |
      /bin/sh -c "
        socat -d -d tcp-listen:5432,fork,reuseaddr tcp-connect:todo-postgres:5432 &
        socat -d -d tcp-listen:6379,fork,reuseaddr tcp-connect:todo-redis:6379 &
        wait
      "
    ports:
      - "127.0.0.1:5432:5432"
      - "127.0.0.1:6379:6379"

volumes:
  postgres_data:
  redis_data:
